package hibernate;
// Generated 2016-12-27 17:26:25 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * C3p0testtable generated by hbm2java
 */
@Entity
@Table(name = "c3p0testtable", catalog = "sendb")
public class C3p0testtable implements java.io.Serializable {

	private Character a;

	public C3p0testtable() {
	}

	public C3p0testtable(Character a) {
		this.a = a;
	}

	@Id

	@Column(name = "a", length = 1)
	public Character getA() {
		return this.a;
	}

	public void setA(Character a) {
		this.a = a;
	}

}
