package hibernate;
// Generated 2016-12-27 17:26:25 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRoles generated by hbm2java
 */
@Entity
@Table(name = "t_roles", catalog = "sendb")
public class TRoles implements java.io.Serializable {

	private Long roleId;
	private String roleCode;
	private String roleName;
	private Integer roleOrder;
	private short status;
	private String remark;
	private Long createUserid;
	private Date createTime;
	private Long updateUserid;
	private Date updateTime;
	private Set TRoleRights = new HashSet(0);
	private Set TUserRoleses = new HashSet(0);

	public TRoles() {
	}

	public TRoles(short status) {
		this.status = status;
	}

	public TRoles(String roleCode, String roleName, Integer roleOrder, short status, String remark, Long createUserid,
			Date createTime, Long updateUserid, Date updateTime, Set TRoleRights, Set TUserRoleses) {
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.roleOrder = roleOrder;
		this.status = status;
		this.remark = remark;
		this.createUserid = createUserid;
		this.createTime = createTime;
		this.updateUserid = updateUserid;
		this.updateTime = updateTime;
		this.TRoleRights = TRoleRights;
		this.TUserRoleses = TUserRoleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "role_id", unique = true, nullable = false)
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_code", length = 20)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "role_name", length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_order")
	public Integer getRoleOrder() {
		return this.roleOrder;
	}

	public void setRoleOrder(Integer roleOrder) {
		this.roleOrder = roleOrder;
	}

	@Column(name = "status", nullable = false)
	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	@Column(name = "remark", length = 300)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "create_userid")
	public Long getCreateUserid() {
		return this.createUserid;
	}

	public void setCreateUserid(Long createUserid) {
		this.createUserid = createUserid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_userid")
	public Long getUpdateUserid() {
		return this.updateUserid;
	}

	public void setUpdateUserid(Long updateUserid) {
		this.updateUserid = updateUserid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRoles")
	public Set getTRoleRights() {
		return this.TRoleRights;
	}

	public void setTRoleRights(Set TRoleRights) {
		this.TRoleRights = TRoleRights;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRoles")
	public Set getTUserRoleses() {
		return this.TUserRoleses;
	}

	public void setTUserRoleses(Set TUserRoleses) {
		this.TUserRoleses = TUserRoleses;
	}

}
