package com.jen.sen.persistence.pojo.system;
// Generated 2016-5-25 16:02:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRight generated by hbm2java
 */
@Entity
@Table(name = "t_right", catalog = "sendb")
public class TRight implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long rightId;
	private String rightCode;
	private Long rightParentId;
	private Short rightOrder;
	private Short rightLevel;
	private String rightName;
	private String rightImg;
	private String rightUrl;
	private String perms;
	private Short status;
	private String remark;
	private Long createUserid;
	private Date createTime;
	private Long updateUserid;
	private Date updateTime;
	private Set<TRoleRight> TRoleRights = new HashSet<TRoleRight>(0);

	public TRight() {
	}

	public TRight(Short status) {
		this.status = status;
	}

	public TRight(String rightCode, Long rightParentId, Short rightOrder,Short rightLevel, String rightName, String rightUrl,String rightImg,
			Short status, String remark, Long createUserid, Date createTime, Long updateUserid, Date updateTime,
			Set<TRoleRight> TRoleRights) {
		this.rightCode = rightCode;
		this.rightParentId = rightParentId;
		this.rightOrder = rightOrder;
		this.rightLevel = rightLevel;
		this.rightName = rightName;
		this.rightUrl = rightUrl;
		this.rightImg= rightImg;
		this.status = status;
		this.remark = remark;
		this.createUserid = createUserid;
		this.createTime = createTime;
		this.updateUserid = updateUserid;
		this.updateTime = updateTime;
		this.TRoleRights = TRoleRights;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "right_id", unique = true, nullable = false)
	public Long getRightId() {
		return this.rightId;
	}

	public void setRightId(Long rightId) {
		this.rightId = rightId;
	}

	@Column(name = "right_code", length = 50)
	public String getRightCode() {
		return this.rightCode;
	}

	public void setRightCode(String rightCode) {
		this.rightCode = rightCode;
	}

	@Column(name = "right_parent_id")
	public Long getRightParentId() {
		return this.rightParentId;
	}

	public void setRightParentId(Long rightParentId) {
		this.rightParentId = rightParentId;
	}

	@Column(name = "right_order")
	public Short getRightOrder() {
		return this.rightOrder;
	}	

	public void setRightOrder(Short rightOrder) {
		this.rightOrder = rightOrder;
	}	
	
	@Column(name = "right_level")
	public Short getRightLevel() {
		return this.rightLevel;
	}
	
	public void setRightLevel(Short rightLevel) {
		this.rightLevel = rightLevel;
	}

	@Column(name = "right_name", length = 50)
	public String getRightName() {
		return this.rightName;
	}

	public void setRightName(String rightName) {
		this.rightName = rightName;
	}

	@Column(name = "right_url")
	public String getRightUrl() {
		return this.rightUrl;
	}

	public void setRightUrl(String rightUrl) {
		this.rightUrl = rightUrl;
	}
	
	@Column(name = "right_img")
	public String getRightImg() {
		return this.rightImg;
	}

	public void setRightImg(String rightImg) {
		this.rightImg = rightImg;
	}

	@Column(name = "status", nullable = false)
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	@Column(name = "remark", length = 300)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "create_userid")
	public Long getCreateUserid() {
		return this.createUserid;
	}

	public void setCreateUserid(Long createUserid) {
		this.createUserid = createUserid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_userid")
	public Long getUpdateUserid() {
		return this.updateUserid;
	}

	public void setUpdateUserid(Long updateUserid) {
		this.updateUserid = updateUserid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TRight")
	public Set<TRoleRight> getTRoleRights() {
		return this.TRoleRights;
	}

	public void setTRoleRights(Set<TRoleRight> TRoleRights) {
		this.TRoleRights = TRoleRights;
	}

	public String getPerms() {
		return perms;
	}

	public void setPerms(String perms) {
		this.perms = perms;
	}
	

}
